package cp36_ExceptionAppPractice;

public class Control {
	
	public void method() throws ArrayIndexOutOfBoundsException {
		System.out.println("\tControl.method()::Start");	
		
		Service s = new Service();
		
		
//		for (int i = 0; i < 4; i++) {
//		try {
//			s.method();
//		} catch(ArrayIndexOutOfBoundsException e) {
//			
//				
//		
//		}
//		
//		}
//	}
		
//		try {
//			
//			s.method();
//			
//		} catch(ArrayIndexOutOfBoundsException e) {
//			System.out.println("		---- catch : Control.method() ----");
//			
//			
//		} finally {
//			System.out.println("		---- finally : Control.method() ----");
//		}
		
	
		
		
		
		System.out.println("\tControl.method()::End");
	}

}
